package com.ivymon.inventory.entity;

import java.util.Date;

public class GoodsInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.GOODS_SEQ
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    private Integer goodsSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.GOODS_NAME
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.ITEM_SEQ
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    private Integer itemSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.PER_QUANTITY
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    private Integer perQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.AMOUNT
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.TWD_UNIT_PRICE
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    private Integer twdUnitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.CURRENCY_UNIT_PRICE
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    private Integer currencyUnitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.MANU_SEQ
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    private Integer manuSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.PURCHASE_TIME
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    private Date purchaseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.TARIFF
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    private Integer tariff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.SHIPPING_FEE
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    private Integer shippingFee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.GOODS_SEQ
     *
     * @return the value of goods_info.GOODS_SEQ
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    public Integer getGoodsSeq() {
        return goodsSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.GOODS_SEQ
     *
     * @param goodsSeq the value for goods_info.GOODS_SEQ
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    public void setGoodsSeq(Integer goodsSeq) {
        this.goodsSeq = goodsSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.GOODS_NAME
     *
     * @return the value of goods_info.GOODS_NAME
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.GOODS_NAME
     *
     * @param goodsName the value for goods_info.GOODS_NAME
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.ITEM_SEQ
     *
     * @return the value of goods_info.ITEM_SEQ
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    public Integer getItemSeq() {
        return itemSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.ITEM_SEQ
     *
     * @param itemSeq the value for goods_info.ITEM_SEQ
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    public void setItemSeq(Integer itemSeq) {
        this.itemSeq = itemSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.PER_QUANTITY
     *
     * @return the value of goods_info.PER_QUANTITY
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    public Integer getPerQuantity() {
        return perQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.PER_QUANTITY
     *
     * @param perQuantity the value for goods_info.PER_QUANTITY
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    public void setPerQuantity(Integer perQuantity) {
        this.perQuantity = perQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.AMOUNT
     *
     * @return the value of goods_info.AMOUNT
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.AMOUNT
     *
     * @param amount the value for goods_info.AMOUNT
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.TWD_UNIT_PRICE
     *
     * @return the value of goods_info.TWD_UNIT_PRICE
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    public Integer getTwdUnitPrice() {
        return twdUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.TWD_UNIT_PRICE
     *
     * @param twdUnitPrice the value for goods_info.TWD_UNIT_PRICE
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    public void setTwdUnitPrice(Integer twdUnitPrice) {
        this.twdUnitPrice = twdUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.CURRENCY_UNIT_PRICE
     *
     * @return the value of goods_info.CURRENCY_UNIT_PRICE
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    public Integer getCurrencyUnitPrice() {
        return currencyUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.CURRENCY_UNIT_PRICE
     *
     * @param currencyUnitPrice the value for goods_info.CURRENCY_UNIT_PRICE
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    public void setCurrencyUnitPrice(Integer currencyUnitPrice) {
        this.currencyUnitPrice = currencyUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.MANU_SEQ
     *
     * @return the value of goods_info.MANU_SEQ
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    public Integer getManuSeq() {
        return manuSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.MANU_SEQ
     *
     * @param manuSeq the value for goods_info.MANU_SEQ
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    public void setManuSeq(Integer manuSeq) {
        this.manuSeq = manuSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.PURCHASE_TIME
     *
     * @return the value of goods_info.PURCHASE_TIME
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    public Date getPurchaseTime() {
        return purchaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.PURCHASE_TIME
     *
     * @param purchaseTime the value for goods_info.PURCHASE_TIME
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    public void setPurchaseTime(Date purchaseTime) {
        this.purchaseTime = purchaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.TARIFF
     *
     * @return the value of goods_info.TARIFF
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    public Integer getTariff() {
        return tariff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.TARIFF
     *
     * @param tariff the value for goods_info.TARIFF
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    public void setTariff(Integer tariff) {
        this.tariff = tariff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.SHIPPING_FEE
     *
     * @return the value of goods_info.SHIPPING_FEE
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    public Integer getShippingFee() {
        return shippingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.SHIPPING_FEE
     *
     * @param shippingFee the value for goods_info.SHIPPING_FEE
     *
     * @mbg.generated Wed Oct 20 10:06:08 CST 2021
     */
    public void setShippingFee(Integer shippingFee) {
        this.shippingFee = shippingFee;
    }
}