package com.ivymon.inventory.entity;

import java.util.ArrayList;
import java.util.List;

public class GoodsItemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_item
     *
     * @mbg.generated Sat Sep 25 11:50:45 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_item
     *
     * @mbg.generated Sat Sep 25 11:50:45 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_item
     *
     * @mbg.generated Sat Sep 25 11:50:45 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_item
     *
     * @mbg.generated Sat Sep 25 11:50:45 CST 2021
     */
    public GoodsItemExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_item
     *
     * @mbg.generated Sat Sep 25 11:50:45 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_item
     *
     * @mbg.generated Sat Sep 25 11:50:45 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_item
     *
     * @mbg.generated Sat Sep 25 11:50:45 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_item
     *
     * @mbg.generated Sat Sep 25 11:50:45 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_item
     *
     * @mbg.generated Sat Sep 25 11:50:45 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_item
     *
     * @mbg.generated Sat Sep 25 11:50:45 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_item
     *
     * @mbg.generated Sat Sep 25 11:50:45 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_item
     *
     * @mbg.generated Sat Sep 25 11:50:45 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_item
     *
     * @mbg.generated Sat Sep 25 11:50:45 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_item
     *
     * @mbg.generated Sat Sep 25 11:50:45 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods_item
     *
     * @mbg.generated Sat Sep 25 11:50:45 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andItemSeqIsNull() {
            addCriterion("ITEM_SEQ is null");
            return (Criteria) this;
        }

        public Criteria andItemSeqIsNotNull() {
            addCriterion("ITEM_SEQ is not null");
            return (Criteria) this;
        }

        public Criteria andItemSeqEqualTo(Integer value) {
            addCriterion("ITEM_SEQ =", value, "itemSeq");
            return (Criteria) this;
        }

        public Criteria andItemSeqNotEqualTo(Integer value) {
            addCriterion("ITEM_SEQ <>", value, "itemSeq");
            return (Criteria) this;
        }

        public Criteria andItemSeqGreaterThan(Integer value) {
            addCriterion("ITEM_SEQ >", value, "itemSeq");
            return (Criteria) this;
        }

        public Criteria andItemSeqGreaterThanOrEqualTo(Integer value) {
            addCriterion("ITEM_SEQ >=", value, "itemSeq");
            return (Criteria) this;
        }

        public Criteria andItemSeqLessThan(Integer value) {
            addCriterion("ITEM_SEQ <", value, "itemSeq");
            return (Criteria) this;
        }

        public Criteria andItemSeqLessThanOrEqualTo(Integer value) {
            addCriterion("ITEM_SEQ <=", value, "itemSeq");
            return (Criteria) this;
        }

        public Criteria andItemSeqIn(List<Integer> values) {
            addCriterion("ITEM_SEQ in", values, "itemSeq");
            return (Criteria) this;
        }

        public Criteria andItemSeqNotIn(List<Integer> values) {
            addCriterion("ITEM_SEQ not in", values, "itemSeq");
            return (Criteria) this;
        }

        public Criteria andItemSeqBetween(Integer value1, Integer value2) {
            addCriterion("ITEM_SEQ between", value1, value2, "itemSeq");
            return (Criteria) this;
        }

        public Criteria andItemSeqNotBetween(Integer value1, Integer value2) {
            addCriterion("ITEM_SEQ not between", value1, value2, "itemSeq");
            return (Criteria) this;
        }

        public Criteria andItemNameIsNull() {
            addCriterion("ITEM_NAME is null");
            return (Criteria) this;
        }

        public Criteria andItemNameIsNotNull() {
            addCriterion("ITEM_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andItemNameEqualTo(String value) {
            addCriterion("ITEM_NAME =", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotEqualTo(String value) {
            addCriterion("ITEM_NAME <>", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameGreaterThan(String value) {
            addCriterion("ITEM_NAME >", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameGreaterThanOrEqualTo(String value) {
            addCriterion("ITEM_NAME >=", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLessThan(String value) {
            addCriterion("ITEM_NAME <", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLessThanOrEqualTo(String value) {
            addCriterion("ITEM_NAME <=", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLike(String value) {
            addCriterion("ITEM_NAME like", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotLike(String value) {
            addCriterion("ITEM_NAME not like", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameIn(List<String> values) {
            addCriterion("ITEM_NAME in", values, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotIn(List<String> values) {
            addCriterion("ITEM_NAME not in", values, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameBetween(String value1, String value2) {
            addCriterion("ITEM_NAME between", value1, value2, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotBetween(String value1, String value2) {
            addCriterion("ITEM_NAME not between", value1, value2, "itemName");
            return (Criteria) this;
        }

        public Criteria andCategorySeqIsNull() {
            addCriterion("CATEGORY_SEQ is null");
            return (Criteria) this;
        }

        public Criteria andCategorySeqIsNotNull() {
            addCriterion("CATEGORY_SEQ is not null");
            return (Criteria) this;
        }

        public Criteria andCategorySeqEqualTo(Integer value) {
            addCriterion("CATEGORY_SEQ =", value, "categorySeq");
            return (Criteria) this;
        }

        public Criteria andCategorySeqNotEqualTo(Integer value) {
            addCriterion("CATEGORY_SEQ <>", value, "categorySeq");
            return (Criteria) this;
        }

        public Criteria andCategorySeqGreaterThan(Integer value) {
            addCriterion("CATEGORY_SEQ >", value, "categorySeq");
            return (Criteria) this;
        }

        public Criteria andCategorySeqGreaterThanOrEqualTo(Integer value) {
            addCriterion("CATEGORY_SEQ >=", value, "categorySeq");
            return (Criteria) this;
        }

        public Criteria andCategorySeqLessThan(Integer value) {
            addCriterion("CATEGORY_SEQ <", value, "categorySeq");
            return (Criteria) this;
        }

        public Criteria andCategorySeqLessThanOrEqualTo(Integer value) {
            addCriterion("CATEGORY_SEQ <=", value, "categorySeq");
            return (Criteria) this;
        }

        public Criteria andCategorySeqIn(List<Integer> values) {
            addCriterion("CATEGORY_SEQ in", values, "categorySeq");
            return (Criteria) this;
        }

        public Criteria andCategorySeqNotIn(List<Integer> values) {
            addCriterion("CATEGORY_SEQ not in", values, "categorySeq");
            return (Criteria) this;
        }

        public Criteria andCategorySeqBetween(Integer value1, Integer value2) {
            addCriterion("CATEGORY_SEQ between", value1, value2, "categorySeq");
            return (Criteria) this;
        }

        public Criteria andCategorySeqNotBetween(Integer value1, Integer value2) {
            addCriterion("CATEGORY_SEQ not between", value1, value2, "categorySeq");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods_item
     *
     * @mbg.generated do_not_delete_during_merge Sat Sep 25 11:50:45 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods_item
     *
     * @mbg.generated Sat Sep 25 11:50:45 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}