package com.ivymon.inventory.entity;

import java.util.ArrayList;
import java.util.List;

public class GoodsCategoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_category
     *
     * @mbg.generated Thu Sep 16 14:54:44 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_category
     *
     * @mbg.generated Thu Sep 16 14:54:44 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_category
     *
     * @mbg.generated Thu Sep 16 14:54:44 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Thu Sep 16 14:54:44 CST 2021
     */
    public GoodsCategoryExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Thu Sep 16 14:54:44 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Thu Sep 16 14:54:44 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Thu Sep 16 14:54:44 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Thu Sep 16 14:54:44 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Thu Sep 16 14:54:44 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Thu Sep 16 14:54:44 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Thu Sep 16 14:54:44 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Thu Sep 16 14:54:44 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Thu Sep 16 14:54:44 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Thu Sep 16 14:54:44 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods_category
     *
     * @mbg.generated Thu Sep 16 14:54:44 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCategorySeqIsNull() {
            addCriterion("CATEGORY_SEQ is null");
            return (Criteria) this;
        }

        public Criteria andCategorySeqIsNotNull() {
            addCriterion("CATEGORY_SEQ is not null");
            return (Criteria) this;
        }

        public Criteria andCategorySeqEqualTo(Integer value) {
            addCriterion("CATEGORY_SEQ =", value, "categorySeq");
            return (Criteria) this;
        }

        public Criteria andCategorySeqNotEqualTo(Integer value) {
            addCriterion("CATEGORY_SEQ <>", value, "categorySeq");
            return (Criteria) this;
        }

        public Criteria andCategorySeqGreaterThan(Integer value) {
            addCriterion("CATEGORY_SEQ >", value, "categorySeq");
            return (Criteria) this;
        }

        public Criteria andCategorySeqGreaterThanOrEqualTo(Integer value) {
            addCriterion("CATEGORY_SEQ >=", value, "categorySeq");
            return (Criteria) this;
        }

        public Criteria andCategorySeqLessThan(Integer value) {
            addCriterion("CATEGORY_SEQ <", value, "categorySeq");
            return (Criteria) this;
        }

        public Criteria andCategorySeqLessThanOrEqualTo(Integer value) {
            addCriterion("CATEGORY_SEQ <=", value, "categorySeq");
            return (Criteria) this;
        }

        public Criteria andCategorySeqIn(List<Integer> values) {
            addCriterion("CATEGORY_SEQ in", values, "categorySeq");
            return (Criteria) this;
        }

        public Criteria andCategorySeqNotIn(List<Integer> values) {
            addCriterion("CATEGORY_SEQ not in", values, "categorySeq");
            return (Criteria) this;
        }

        public Criteria andCategorySeqBetween(Integer value1, Integer value2) {
            addCriterion("CATEGORY_SEQ between", value1, value2, "categorySeq");
            return (Criteria) this;
        }

        public Criteria andCategorySeqNotBetween(Integer value1, Integer value2) {
            addCriterion("CATEGORY_SEQ not between", value1, value2, "categorySeq");
            return (Criteria) this;
        }

        public Criteria andCategoryNameIsNull() {
            addCriterion("CATEGORY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCategoryNameIsNotNull() {
            addCriterion("CATEGORY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryNameEqualTo(String value) {
            addCriterion("CATEGORY_NAME =", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameNotEqualTo(String value) {
            addCriterion("CATEGORY_NAME <>", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameGreaterThan(String value) {
            addCriterion("CATEGORY_NAME >", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameGreaterThanOrEqualTo(String value) {
            addCriterion("CATEGORY_NAME >=", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameLessThan(String value) {
            addCriterion("CATEGORY_NAME <", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameLessThanOrEqualTo(String value) {
            addCriterion("CATEGORY_NAME <=", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameLike(String value) {
            addCriterion("CATEGORY_NAME like", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameNotLike(String value) {
            addCriterion("CATEGORY_NAME not like", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameIn(List<String> values) {
            addCriterion("CATEGORY_NAME in", values, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameNotIn(List<String> values) {
            addCriterion("CATEGORY_NAME not in", values, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameBetween(String value1, String value2) {
            addCriterion("CATEGORY_NAME between", value1, value2, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameNotBetween(String value1, String value2) {
            addCriterion("CATEGORY_NAME not between", value1, value2, "categoryName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods_category
     *
     * @mbg.generated do_not_delete_during_merge Thu Sep 16 14:54:44 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods_category
     *
     * @mbg.generated Thu Sep 16 14:54:44 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}