package com.ivymon.inventory.entity;

public class GoodsItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_item.ITEM_SEQ
     *
     * @mbg.generated Thu Sep 16 14:54:26 CST 2021
     */
    private Integer itemSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_item.ITEM_NAME
     *
     * @mbg.generated Thu Sep 16 14:54:26 CST 2021
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_item.CATEGORY_SEQ
     *
     * @mbg.generated Thu Sep 16 14:54:26 CST 2021
     */
    private Integer categorySeq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_item.ITEM_SEQ
     *
     * @return the value of goods_item.ITEM_SEQ
     *
     * @mbg.generated Thu Sep 16 14:54:26 CST 2021
     */
    public Integer getItemSeq() {
        return itemSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_item.ITEM_SEQ
     *
     * @param itemSeq the value for goods_item.ITEM_SEQ
     *
     * @mbg.generated Thu Sep 16 14:54:26 CST 2021
     */
    public void setItemSeq(Integer itemSeq) {
        this.itemSeq = itemSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_item.ITEM_NAME
     *
     * @return the value of goods_item.ITEM_NAME
     *
     * @mbg.generated Thu Sep 16 14:54:26 CST 2021
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_item.ITEM_NAME
     *
     * @param itemName the value for goods_item.ITEM_NAME
     *
     * @mbg.generated Thu Sep 16 14:54:26 CST 2021
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_item.CATEGORY_SEQ
     *
     * @return the value of goods_item.CATEGORY_SEQ
     *
     * @mbg.generated Thu Sep 16 14:54:26 CST 2021
     */
    public Integer getCategorySeq() {
        return categorySeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_item.CATEGORY_SEQ
     *
     * @param categorySeq the value for goods_item.CATEGORY_SEQ
     *
     * @mbg.generated Thu Sep 16 14:54:26 CST 2021
     */
    public void setCategorySeq(Integer categorySeq) {
        this.categorySeq = categorySeq;
    }
}