package com.ivymon.inventory.entity;

public class GoodsCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_category.CATEGORY_SEQ
     *
     * @mbg.generated Thu Sep 16 14:54:44 CST 2021
     */
    private Integer categorySeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_category.CATEGORY_NAME
     *
     * @mbg.generated Thu Sep 16 14:54:44 CST 2021
     */
    private String categoryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_category.CATEGORY_SEQ
     *
     * @return the value of goods_category.CATEGORY_SEQ
     *
     * @mbg.generated Thu Sep 16 14:54:44 CST 2021
     */
    public Integer getCategorySeq() {
        return categorySeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_category.CATEGORY_SEQ
     *
     * @param categorySeq the value for goods_category.CATEGORY_SEQ
     *
     * @mbg.generated Thu Sep 16 14:54:44 CST 2021
     */
    public void setCategorySeq(Integer categorySeq) {
        this.categorySeq = categorySeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_category.CATEGORY_NAME
     *
     * @return the value of goods_category.CATEGORY_NAME
     *
     * @mbg.generated Thu Sep 16 14:54:44 CST 2021
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_category.CATEGORY_NAME
     *
     * @param categoryName the value for goods_category.CATEGORY_NAME
     *
     * @mbg.generated Thu Sep 16 14:54:44 CST 2021
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
}