package com.ivymon.inventory.entity;

import java.util.Date;

public class Manufacture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacture.MANU_SEQ
     *
     * @mbg.generated Thu Sep 16 14:54:01 CST 2021
     */
    private Integer manuSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacture.MANU_NAME
     *
     * @mbg.generated Thu Sep 16 14:54:01 CST 2021
     */
    private String manuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacture.NATION
     *
     * @mbg.generated Thu Sep 16 14:54:01 CST 2021
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacture.CURRENCY
     *
     * @mbg.generated Thu Sep 16 14:54:01 CST 2021
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacture.CREAT_TIME
     *
     * @mbg.generated Thu Sep 16 14:54:01 CST 2021
     */
    private Date creatTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacture.MANU_SEQ
     *
     * @return the value of manufacture.MANU_SEQ
     *
     * @mbg.generated Thu Sep 16 14:54:01 CST 2021
     */
    public Integer getManuSeq() {
        return manuSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacture.MANU_SEQ
     *
     * @param manuSeq the value for manufacture.MANU_SEQ
     *
     * @mbg.generated Thu Sep 16 14:54:01 CST 2021
     */
    public void setManuSeq(Integer manuSeq) {
        this.manuSeq = manuSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacture.MANU_NAME
     *
     * @return the value of manufacture.MANU_NAME
     *
     * @mbg.generated Thu Sep 16 14:54:01 CST 2021
     */
    public String getManuName() {
        return manuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacture.MANU_NAME
     *
     * @param manuName the value for manufacture.MANU_NAME
     *
     * @mbg.generated Thu Sep 16 14:54:01 CST 2021
     */
    public void setManuName(String manuName) {
        this.manuName = manuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacture.NATION
     *
     * @return the value of manufacture.NATION
     *
     * @mbg.generated Thu Sep 16 14:54:01 CST 2021
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacture.NATION
     *
     * @param nation the value for manufacture.NATION
     *
     * @mbg.generated Thu Sep 16 14:54:01 CST 2021
     */
    public void setNation(String nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacture.CURRENCY
     *
     * @return the value of manufacture.CURRENCY
     *
     * @mbg.generated Thu Sep 16 14:54:01 CST 2021
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacture.CURRENCY
     *
     * @param currency the value for manufacture.CURRENCY
     *
     * @mbg.generated Thu Sep 16 14:54:01 CST 2021
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacture.CREAT_TIME
     *
     * @return the value of manufacture.CREAT_TIME
     *
     * @mbg.generated Thu Sep 16 14:54:01 CST 2021
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacture.CREAT_TIME
     *
     * @param creatTime the value for manufacture.CREAT_TIME
     *
     * @mbg.generated Thu Sep 16 14:54:01 CST 2021
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }
}