package com.ivymon.inventory.entity;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.ID
     *
     * @mbg.generated Wed May 05 11:15:24 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.NAME
     *
     * @mbg.generated Wed May 05 11:15:24 CST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.ID
     *
     * @return the value of product.ID
     *
     * @mbg.generated Wed May 05 11:15:24 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.ID
     *
     * @param id the value for product.ID
     *
     * @mbg.generated Wed May 05 11:15:24 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.NAME
     *
     * @return the value of product.NAME
     *
     * @mbg.generated Wed May 05 11:15:24 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.NAME
     *
     * @param name the value for product.NAME
     *
     * @mbg.generated Wed May 05 11:15:24 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }
}