package com.ivymon.inventory.entity.mapper;

import com.ivymon.inventory.entity.GoodsItem;
import com.ivymon.inventory.entity.GoodsItemExample;

public interface GoodsItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_item
     *
     * @mbg.generated Thu Sep 16 14:54:26 CST 2021
     */
    long countByExample(GoodsItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_item
     *
     * @mbg.generated Thu Sep 16 14:54:26 CST 2021
     */
    int deleteByPrimaryKey(Integer itemSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_item
     *
     * @mbg.generated Thu Sep 16 14:54:26 CST 2021
     */
    int insert(GoodsItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_item
     *
     * @mbg.generated Thu Sep 16 14:54:26 CST 2021
     */
    int insertSelective(GoodsItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_item
     *
     * @mbg.generated Thu Sep 16 14:54:26 CST 2021
     */
    GoodsItem selectByPrimaryKey(Integer itemSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_item
     *
     * @mbg.generated Thu Sep 16 14:54:26 CST 2021
     */
    int updateByPrimaryKeySelective(GoodsItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_item
     *
     * @mbg.generated Thu Sep 16 14:54:26 CST 2021
     */
    int updateByPrimaryKey(GoodsItem record);
}